### ISSUE TITLE
Landsat-Classification-Using-Convolution-Neural-Network

### ISSUE THREAD

**Issue by zafor44** [PratyushTripathy/Landsat-Classification-Using-Convolution-Neural-Network#4] opened 2022-05-03 14:25 UTC
features = imageChipsFromFile(feature_file, x_size=7, y_size=7)

""" Update: 29 May 2021
Since I added this code chunk later, I wanted to make least 
possible changes in the remaining sections. The below line changes
the index of the channels. This will be undone at a later stage.
"""
features = np.rollaxis(features, 3, 1)

Error
NameError                                 Traceback (most recent call last)
~\R\WIN-LI~1\3.6/ipykernel_18024/3305981793.py in <module>
      1 # create feature chips using pyrsgis
----> 2 features = imageChipsFromFile(feature_file, x_size=7, y_size=7)
      3 
      4 """ Update: 29 May 2021
      5 Since I added this code chunk later, I wanted to make least

~\anaconda3\lib\site-packages\pyrsgis\ml\__init__.py in imageChipsFromFile(infile, y_size, x_size)
    205     ds, data_arr = read(infile)
    206 
--> 207     return(imageChipsFromArray(data_arr, y_size=y_size, x_size=x_size))

~\anaconda3\lib\site-packages\pyrsgis\ml\__init__.py in imageChipsFromArray(data_array, x_size, y_size)
    132     # if array is a multi band image
    133     elif len(data_array.shape) > 2:
--> 134         data_array = copy.copy(data_array)
    135         data_array = np.rollaxis(data_array, 0, 3)
    136 

NameError: name 'copy' is not defined

how to solve it sir.

**Comment by PratyushTripathy** [comment] 2022-05-03 15:26
Duplicate of #2 
Option 1 - locate this file on your computer and add `import copy` in the beginning.
~\anaconda3\lib\site-packages\pyrsgis\ml_init_.py

Option 2 - replace `copy.copy` with `deepcopy`. See [here](https://github.com/PratyushTripathy/Landsat-Classification-Using-Convolution-Neural-Network/issues/2#issuecomment-934073206).

**Closed as completed by PratyushTripathy** 2022-05-03 15:26 UTC
