### ISSUE TITLE
NameError: name 'copy' is not defined

### ISSUE THREAD

**Issue by adenant** [PratyushTripathy/Landsat-Classification-Using-Convolution-Neural-Network#2] opened 2021-10-05 03:29 UTC
Hi,

Thank you for the tutorial. I tried to replicate the procedure, but when I ran the script for image chipping, I experienced the following error: "NameError: name 'copy' is not defined" (Image capture attached). I'm using Python 3.9.7. Do you know what causing the problem  might be?  Thank you.

![image](https://user-images.githubusercontent.com/3861109/135955143-6c69d112-94df-456c-b494-68e31277edfd.png)

**Comment by PratyushTripathy** [comment] 2021-10-05 05:17
Hi @adenant, 

Thank you for flagging this bug. You are doing it right, the problem is in the pyrsgis module and will be fixed in the next version. Till then could you please manually fix this on your system? Here's how:

1. Find and open the "*pyrsgis\ml\__init__.py" (you can see the full path the in the error message).
2. Go to line 134 and replace `copy.copy` with `deepcopy`.

Hope this works. Let me know if it does not.

**Comment by adenant** [comment] 2021-10-06 04:20
Hi @PratyushTripathy 

Thanks for the response. I fixed the issue, and the code for the first part ran. However, when I started the second part, there were no image chips found in the imagechip folder, is it an issue with the pyrgis as well?

**Comment by PratyushTripathy** [comment] 2021-10-06 04:25
@adenant Please read the Medium blog carefully. If you use this function, there won't be any image chips in the folder. Image chips will be generated if you use the QGIS plugin. If you use this, it will directly load the chips as array and store in the 'features' variable.

**Closed as completed by PratyushTripathy** 2021-10-06 04:25 UTC
